# Generated by Django 4.0.2 on 2022-02-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('phonenumber', models.BigIntegerField()),
                ('is_verified', models.BooleanField()),
            ],
        ),
    ]
