# Generated by Django 4.0.2 on 2022-03-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=100),
        ),
        migrations.AddField(
            model_name='note',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
