# Generated by Django 4.0.2 on 2022-04-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_archive_note_color_note_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_id', models.CharField(max_length=100)),
                ('note', models.ManyToManyField(to='notes.Note')),
            ],
        ),
    ]
