# Generated by Django 4.0.2 on 2022-04-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='color_id',
        ),
        migrations.AddField(
            model_name='label',
            name='color',
            field=models.CharField(default='white', max_length=100),
        ),
    ]
