# Generated by Django 4.0.2 on 2022-04-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_remove_label_color_id_label_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='label',
            field=models.ManyToManyField(to='notes.Label'),
        ),
    ]
