# Generated by Django 4.0.2 on 2022-04-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_remove_label_note_note_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='label',
        ),
        migrations.AddField(
            model_name='label',
            name='note',
            field=models.ManyToManyField(to='notes.Note'),
        ),
    ]
