# Generated by Django 4.0.2 on 2022-04-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_remove_note_label_label_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='note',
            field=models.ManyToManyField(related_name='note_set', to='notes.Note'),
        ),
    ]
